/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MediaShuttleApi) {
      root.MediaShuttleApi = {};
    }
    root.MediaShuttleApi.AzureBlobStorage = factory(root.MediaShuttleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The AzureBlobStorage model module.
   * @module model/AzureBlobStorage
   * @version 1.13.3
   */

  /**
   * Constructs a new <code>AzureBlobStorage</code>.
   * Storage configuration details specific to Azure Blob storage.
   * @alias module:model/AzureBlobStorage
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>AzureBlobStorage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AzureBlobStorage} obj Optional instance to populate.
   * @return {module:model/AzureBlobStorage} The populated <code>AzureBlobStorage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('accountName'))
        obj.accountName = ApiClient.convertToType(data['accountName'], 'String');
      if (data.hasOwnProperty('accessKey'))
        obj.accessKey = ApiClient.convertToType(data['accessKey'], 'String');
      if (data.hasOwnProperty('container'))
        obj.container = ApiClient.convertToType(data['container'], 'String');
      if (data.hasOwnProperty('filePrefix'))
        obj.filePrefix = ApiClient.convertToType(data['filePrefix'], 'String');
    }
    return obj;
  }

  /**
   * The Azure account owning the Blob Storage.
   * @member {String} accountName
   */
  exports.prototype.accountName = undefined;

  /**
   * The access key for the Blob Storage.
   * @member {String} accessKey
   */
  exports.prototype.accessKey = undefined;

  /**
   * The Blob Storage container.
   * @member {String} container
   */
  exports.prototype.container = undefined;

  /**
   * Prefix to prepend to files transfered to this location. Can be used to drop all files into a sub-directory.
   * @member {String} filePrefix
   * @default ''
   */
  exports.prototype.filePrefix = '';


  return exports;

}));
