/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MediaShuttleApi) {
      root.MediaShuttleApi = {};
    }
    root.MediaShuttleApi.Portal = factory(root.MediaShuttleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Portal model module.
   * @module model/Portal
   * @version 1.13.3
   */

  /**
   * Constructs a new <code>Portal</code>.
   * A Media Shuttle portal registered to an account.
   * @alias module:model/Portal
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Portal</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Portal} obj Optional instance to populate.
   * @return {module:model/Portal} The populated <code>Portal</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('createdOn'))
        obj.createdOn = ApiClient.convertToType(data['createdOn'], 'Date');
      if (data.hasOwnProperty('lastModifiedOn'))
        obj.lastModifiedOn = ApiClient.convertToType(data['lastModifiedOn'], 'Date');
      if (data.hasOwnProperty('authentication'))
        obj.authentication = ApiClient.convertToType(data['authentication'], Object);
      if (data.hasOwnProperty('linkAuthentication'))
        obj.linkAuthentication = ApiClient.convertToType(data['linkAuthentication'], Object);
    }
    return obj;
  }

  /**
   * Unique identifier representing a portal.
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * The portal name.
   * @member {String} name
   * @default 'Share Portal n'
   */
  exports.prototype.name = 'Share Portal n';

  /**
   * The access URL for the portal. The URL prefix cannot exceed 63 characters, must contain only alphanumeric characters and cannot start or end with a dash (-) and must end in \".mediashuttle.com\".
   * @member {String} url
   * @default 'random.mediashuttle.com'
   */
  exports.prototype.url = 'random.mediashuttle.com';

  /**
   * Media Shuttle portal type.
   * @member {module:model/Portal.TypeEnum} type
   * @default 'share'
   */
  exports.prototype.type = 'share';

  /**
   * The date of portal creation.
   * @member {Date} createdOn
   */
  exports.prototype.createdOn = undefined;

  /**
   * The date the portal was last modified.
   * @member {Date} lastModifiedOn
   */
  exports.prototype.lastModifiedOn = undefined;

  /**
   * The authentication schemes for the portal, where a Share portal cannot be unauthenticated.
   * @member {Object} authentication
   */
  exports.prototype.authentication = undefined;

  /**
   * The authentication options for download, upload, and token based links. Only applicable when portal authentication is enabled.
   * @member {Object} linkAuthentication
   */
  exports.prototype.linkAuthentication = undefined;



  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "send"
     * @const
     */
    send: "send",

    /**
     * value: "share"
     * @const
     */
    share: "share",

    /**
     * value: "submit"
     * @const
     */
    submit: "submit"
  };

  return exports;

}));
