/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MediaShuttleApi) {
      root.MediaShuttleApi = {};
    }
    root.MediaShuttleApi.PortalMember = factory(root.MediaShuttleApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PortalMember model module.
   * @module model/PortalMember
   * @version 1.13.3
   */

  /**
   * Constructs a new <code>PortalMember</code>.
   * An object representing user membership on the portal
   * @alias module:model/PortalMember
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PortalMember</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PortalMember} obj Optional instance to populate.
   * @return {module:model/PortalMember} The populated <code>PortalMember</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('expiresOn'))
        obj.expiresOn = ApiClient.convertToType(data['expiresOn'], 'String');
      if (data.hasOwnProperty('portalPermissions'))
        obj.portalPermissions = ApiClient.convertToType(data['portalPermissions'], Object);
    }
    return obj;
  }

  /**
   * The email address of the portal member
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * The role the user is assigned on this portal. Ops is short for operations administrator, and represents an administrator of portal activity. Members are allowed to use the portal to transfer files. The operations administrator role includes the member role.
   * @member {module:model/PortalMember.RoleEnum} role
   * @default 'Member'
   */
  exports.prototype.role = 'Member';

  /**
   * The date and time the portal member account expires. If the portal member account is not set to expire, this field will not be present.
   * @member {String} expiresOn
   */
  exports.prototype.expiresOn = undefined;

  /**
   * The user's permissions on the portal
   * @member {Object} portalPermissions
   */
  exports.prototype.portalPermissions = undefined;



  /**
   * Allowed values for the <code>role</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RoleEnum = {
    /**
     * value: "Member"
     * @const
     */
    member: "Member",

    /**
     * value: "Ops"
     * @const
     */
    ops: "Ops"
  };

  return exports;

}));
