/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MediaShuttleApi);
  }
}(this, function(expect, MediaShuttleApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LocalStorage', function() {
      beforeEach(function() {
        instance = new MediaShuttleApi.LocalStorage();
      });

      it('should create an instance of LocalStorage', function() {
        // TODO: update the code to test LocalStorage
        expect(instance).to.be.a(MediaShuttleApi.LocalStorage);
      });

      it('should have the property useMultiplePorts (base name: "useMultiplePorts")', function() {
        // TODO: update the code to test the property useMultiplePorts
        expect(instance).to.have.property('useMultiplePorts');
        // expect(instance.useMultiplePorts).to.be(expectedValueLiteral);
      });

      it('should have the property hostname (base name: "hostname")', function() {
        // TODO: update the code to test the property hostname
        expect(instance).to.have.property('hostname');
        // expect(instance.hostname).to.be(expectedValueLiteral);
      });

      it('should have the property storageServerVersion (base name: "storageServerVersion")', function() {
        // TODO: update the code to test the property storageServerVersion
        expect(instance).to.have.property('storageServerVersion');
        // expect(instance.storageServerVersion).to.be(expectedValueLiteral);
      });

      it('should have the property installationKey (base name: "installationKey")', function() {
        // TODO: update the code to test the property installationKey
        expect(instance).to.have.property('installationKey');
        // expect(instance.installationKey).to.be(expectedValueLiteral);
      });

    });
  });

}));
