/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MediaShuttleApi);
  }
}(this, function(expect, MediaShuttleApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('PackageTokenRequest', function() {
      beforeEach(function() {
        instance = new MediaShuttleApi.PackageTokenRequest();
      });

      it('should create an instance of PackageTokenRequest', function() {
        // TODO: update the code to test PackageTokenRequest
        expect(instance).to.be.a(MediaShuttleApi.PackageTokenRequest);
      });

      it('should have the property user (base name: "user")', function() {
        // TODO: update the code to test the property user
        expect(instance).to.have.property('user');
        // expect(instance.user).to.be(expectedValueLiteral);
      });

      it('should have the property grants (base name: "grants")', function() {
        // TODO: update the code to test the property grants
        expect(instance).to.have.property('grants');
        // expect(instance.grants).to.be(expectedValueLiteral);
      });

      it('should have the property expiresOn (base name: "expiresOn")', function() {
        // TODO: update the code to test the property expiresOn
        expect(instance).to.have.property('expiresOn');
        // expect(instance.expiresOn).to.be(expectedValueLiteral);
      });

      it('should have the property destinationPath (base name: "destinationPath")', function() {
        // TODO: update the code to test the property destinationPath
        expect(instance).to.have.property('destinationPath');
        // expect(instance.destinationPath).to.be(expectedValueLiteral);
      });

      it('should have the property notifications (base name: "notifications")', function() {
        // TODO: update the code to test the property notifications
        expect(instance).to.have.property('notifications');
        // expect(instance.notifications).to.be(expectedValueLiteral);
      });

    });
  });

}));
