/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MediaShuttleApi);
  }
}(this, function(expect, MediaShuttleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MediaShuttleApi.PortalsApi();
  });

  describe('(package)', function() {
    describe('PortalsApi', function() {
      describe('addUserToPortal', function() {
        it('should call addUserToPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for addUserToPortal call and complete the assertions
          /*
          var portalId = "portalId_example";
          var opts = {};
          opts.user = new MediaShuttleApi.PortalMember();
          opts.user.email = "user@example.com";
          opts.user.role = "Member";
          opts.user.expiresOn = "2019-02-22T11:35:40.000Z";
          opts.user.portalPermissions = ;

          instance.addUserToPortal(portalId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalMember);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("user@example.com");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("Member");
            expect(data.expiresOn).to.be.a('string');
            expect(data.expiresOn).to.be("2019-02-22T11:35:40.000Z");
            expect(data.portalPermissions).to.be.a(Object);
            expect(data.portalPermissions).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('assignStorageToPortal', function() {
        it('should call assignStorageToPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for assignStorageToPortal call and complete the assertions
          /*
          var portalId = "portalId_example";
          var storageId = "storageId_example";
          var opts = {};
          opts.repositoryPath = new MediaShuttleApi.PortalStorage();
          opts.repositoryPath.storageId = "35460d47-019b-4e06-8108-18343b235108";
          opts.repositoryPath.repositoryPath = "/example/repository/path";

          instance.assignStorageToPortal(portalId, storageId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalStorage);
            expect(data.storageId).to.be.a('string');
            expect(data.storageId).to.be("35460d47-019b-4e06-8108-18343b235108");
            expect(data.repositoryPath).to.be.a('string');
            expect(data.repositoryPath).to.be("/example/repository/path");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('assignUserToPortal', function() {
        it('should call assignUserToPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for assignUserToPortal call and complete the assertions
          /*
          var portalId = "portalId_example";
          var email = "email_example";
          var opts = {};
          opts.role = new MediaShuttleApi.PortalMember();
          opts.role.email = "user@example.com";
          opts.role.role = "Member";
          opts.role.expiresOn = "2019-02-22T11:35:40.000Z";
          opts.role.portalPermissions = ;

          instance.assignUserToPortal(portalId, email, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalMember);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("user@example.com");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("Member");
            expect(data.expiresOn).to.be.a('string');
            expect(data.expiresOn).to.be("2019-02-22T11:35:40.000Z");
            expect(data.portalPermissions).to.be.a(Object);
            expect(data.portalPermissions).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('createPortal', function() {
        it('should call createPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for createPortal call and complete the assertions
          /*
          var opts = {};
          opts.portal = new MediaShuttleApi.Portal();
          opts.portal.id = "35460d47-019b-4e06-8108-18343b235108";
          opts.portal.name = "New Portal";
          opts.portal.url = "new-portal.mediashuttle.com";
          opts.portal.type = "share";
          opts.portal.authentication = ;
          opts.portal.linkAuthentication = ;

          instance.createPortal(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.Portal);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("35460d47-019b-4e06-8108-18343b235108");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("New Portal");
            expect(data.url).to.be.a('string');
            expect(data.url).to.be("new-portal.mediashuttle.com");
            expect(data.type).to.be.a('string');
            expect(data.type).to.be("share");
            expect(data.createdOn).to.be.a(Date);
            expect(data.createdOn).to.be(1985-04-12T23:20:50.52.000Z);
            expect(data.lastModifiedOn).to.be.a(Date);
            expect(data.lastModifiedOn).to.be(1985-04-12T23:20:50.52.000Z);
            expect(data.authentication).to.be.a(Object);
            expect(data.authentication).to.be();
            expect(data.linkAuthentication).to.be.a(Object);
            expect(data.linkAuthentication).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getMembersFromPortal', function() {
        it('should call getMembersFromPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for getMembersFromPortal call and complete the assertions
          /*
          var portalId = "portalId_example";

          instance.getMembersFromPortal(portalId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalMemberRequest);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MediaShuttleApi.PortalMemberResponse);
                expect(data.email).to.be.a('string');
                expect(data.email).to.be("user@example.com");

                      }
            }
            expect(data.error).to.be.a(Object);
            expect(data.error).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPortalMember', function() {
        it('should call getPortalMember successfully', function(done) {
          // TODO: uncomment, update parameter values for getPortalMember call and complete the assertions
          /*
          var portalId = "portalId_example";
          var email = "email_example";

          instance.getPortalMember(portalId, email, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalMember);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("user@example.com");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("Member");
            expect(data.expiresOn).to.be.a('string');
            expect(data.expiresOn).to.be("2019-02-22T11:35:40.000Z");
            expect(data.portalPermissions).to.be.a(Object);
            expect(data.portalPermissions).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPortalStorage', function() {
        it('should call getPortalStorage successfully', function(done) {
          // TODO: uncomment, update parameter values for getPortalStorage call and complete the assertions
          /*
          var portalId = "portalId_example";

          instance.getPortalStorage(portalId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalStorageList);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MediaShuttleApi.PortalStorage);
                expect(data.storageId).to.be.a('string');
                expect(data.storageId).to.be("35460d47-019b-4e06-8108-18343b235108");
                expect(data.repositoryPath).to.be.a('string');
                expect(data.repositoryPath).to.be("/example/repository/path");

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getPortals', function() {
        it('should call getPortals successfully', function(done) {
          // TODO: uncomment, update parameter values for getPortals call and complete the assertions
          /*
          var opts = {};
          opts.url = "url_example";

          instance.getPortals(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalList);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MediaShuttleApi.Portal);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("35460d47-019b-4e06-8108-18343b235108");
                expect(data.name).to.be.a('string');
                expect(data.name).to.be("New Portal");
                expect(data.url).to.be.a('string');
                expect(data.url).to.be("new-portal.mediashuttle.com");
                expect(data.type).to.be.a('string');
                expect(data.type).to.be("share");
                expect(data.createdOn).to.be.a(Date);
                expect(data.createdOn).to.be(1985-04-12T23:20:50.52.000Z);
                expect(data.lastModifiedOn).to.be.a(Date);
                expect(data.lastModifiedOn).to.be(1985-04-12T23:20:50.52.000Z);
                expect(data.authentication).to.be.a(Object);
                expect(data.authentication).to.be();
                expect(data.linkAuthentication).to.be.a(Object);
                expect(data.linkAuthentication).to.be();

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('removeUserFromPortal', function() {
        it('should call removeUserFromPortal successfully', function(done) {
          // TODO: uncomment, update parameter values for removeUserFromPortal call and complete the assertions
          /*
          var portalId = "portalId_example";
          var email = "email_example";

          instance.removeUserFromPortal(portalId, email, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.PortalMember);
            expect(data.email).to.be.a('string');
            expect(data.email).to.be("user@example.com");
            expect(data.role).to.be.a('string');
            expect(data.role).to.be("Member");
            expect(data.expiresOn).to.be.a('string');
            expect(data.expiresOn).to.be("2019-02-22T11:35:40.000Z");
            expect(data.portalPermissions).to.be.a(Object);
            expect(data.portalPermissions).to.be();

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
