/*
 * Media Shuttle API
 * Signiant's **Media Shuttle Management API** endpoints allows you to automate portal and storage management and view active transfers using your own web applications.  The **System-to-Person API** allows you to create upload and download links directly from other applications, letting you accelerate file transfers through Media Shuttle.  For more information about getting started with the Media Shuttle API, read our [Getting Started Guide](http://developer.signiant.com/msapi/getting-started.html).  ---   You can test API endpoints using your Media Shuttle subscription by generating an API key from your IT Administration user menu, in the **Developer** section.  Once you have generated an API key, click the **Authorize** button, and enter your API key in the **Value** field, and click **Authorize** to enable the examples. 
 *
 * OpenAPI spec version: 1.13.3
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MediaShuttleApi);
  }
}(this, function(expect, MediaShuttleApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MediaShuttleApi.TransfersApi();
  });

  describe('(package)', function() {
    describe('TransfersApi', function() {
      describe('getTransfers', function() {
        it('should call getTransfers successfully', function(done) {
          // TODO: uncomment, update parameter values for getTransfers call and complete the assertions
          /*
          var state = "state_example";
          var opts = {};
          opts.portalId = "portalId_example";

          instance.getTransfers(state, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MediaShuttleApi.TransferList);
            {
              let dataCtr = data.items;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(MediaShuttleApi.Transfer);
                expect(data.id).to.be.a('string');
                expect(data.id).to.be("69ccc2a2-170d-4866-aca6-9bb1a5944163");
                expect(data.portalId).to.be.a('string');
                expect(data.portalId).to.be("61a1d109-d553-4052-9c0e-814f1ded4b68");
                expect(data.packageId).to.be.a('string');
                expect(data.packageId).to.be("m62kqJGGOyGauacKIQUYNO");
                expect(data.state).to.be.a('string');
                expect(data.state).to.be("active");
                expect(data.protocol).to.be.a('string');
                expect(data.protocol).to.be("mxwan");
                expect(data.connectedServer).to.be.a('string');
                expect(data.connectedServer).to.be("your.storage.example.com");
                expect(data.direction).to.be.a('string');
                expect(data.direction).to.be("download");
                expect(data.user).to.be.a(MediaShuttleApi.User);
                      expect(data.user.email).to.be.a('string');
                  expect(data.user.email).to.be("user@example.com");
                expect(data.startTime).to.be.a('string');
                expect(data.startTime).to.be("2017-12-11T15:00:56.664Z");
                expect(data.activeTransferDetails).to.be.a(Object);
                expect(data.activeTransferDetails).to.be();

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
